name: tests
on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '**/README.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [  ubuntu-latest, macos-latest ]
        include:
        - os: ubuntu-latest
        - os: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies for kcov
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake g++ libcurl4-openssl-dev libelf-dev libdw-dev libunwind-dev
    
    - name: Build and install kcov
      run: |
        git clone https://github.com/SimonKagstrom/kcov.git
        cd kcov
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install
    
    - name: 'install bashunit and kcov'
      run: |
        #sudo apt update && sudo apt-get -y install kcov
        mkdir lib
        curl -s https://bashunit.typeddevs.com/install.sh | bash
        chmod +x lib/bashunit  # Ensure script is executable

    - name: 'run tests in parallel'
      run: |
        mkdir -p coverage
        kcov --include-pattern=./src coverage/ ./tests.sh
