name: tests
on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '**/README.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [  ubuntu-latest, macos-latest ]
        include:
        - os: ubuntu-latest
        - os: macos-latest
    steps:
    - uses: actions/checkout@v4


    - name: 'install bashunit and kcov'
      run: |
        mkdir lib
        curl -s https://bashunit.typeddevs.com/install.sh | bash
        chmod +x lib/bashunit
    
    - name: Run tests with kcov Docker image
      run: |
        mkdir -p coverage
        docker run --rm \
          -v "$(pwd):/project" \
          -v "$(pwd)/coverage:/coverage" \
          --entrypoint kcov \
          kcov/kcov \
          --include-pattern=/project/src \
          /coverage \
          /project/tests.sh
